version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"

  - package-ecosystem: "uv"
    directories: ["/"]
    schedule:
      interval: "weekly"
    groups:
      uv:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
