name: 'Generate Dependabot Config'
description: 'Generates a dependabot.yml file based on the detected package ecosystems in the repository.'
inputs:
  scan-path:
    description: 'The path to scan for dependency files.'
    required: false
    default: '.'
  interval:
    description: 'The update interval for dependencies.'
    required: false
    default: 'weekly'
  ignore-dirs:
    description: 'A comma-separated string of relative paths to ignore.'
    required: false
    default: ''
  custom-map:
    description: 'JSON string to extend the default ecosystem map.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: false
    - name: Generate dependabot.yml
      id: generate
      shell: bash
      run: |
        go run ${{ github.action_path }}/cmd/dependabot-generate \
          --scan-path "${{ inputs.scan-path }}" \
          --interval "${{ inputs.interval }}" \
          --ignore-dirs "${{ inputs.ignore-dirs }}" \
          --custom-map '${{ inputs.custom-map }}'
