name: 'Generate Dependabot Config'
description: 'Generates a dependabot.yml file based on the detected package ecosystems in the repository.'
inputs:
  root-path:
    description: 'The path to scan for dependency files.'
    required: false
    default: '.'
  exclude-paths:
    description: 'A comma-separated string of relative paths to ignore.'
    required: false
    default: ''
  update-interval:
    description: 'The update interval for dependencies.'
    required: false
    default: 'weekly'
  custom-map:
    description: 'JSON string to extend the default ecosystem map.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--root-path=${{ inputs.root-path }}'
    - '--update-interval=${{ inputs.update-interval }}'
    - '--exclude-paths=${{ inputs.exclude-paths }}'
    - '--custom-map=${{ inputs.custom-map }}'

